### ISSUE TITLE
_pickle.UnpicklingError: invalid load key

### ISSUE THREAD

**Issue by hongyuan-wang** [InstantID/InstantID#161]
### **Issue description:**
I am running instantID in stable-diffusion-webui, and control_instant_id_sdxl is downloaded from https://huggingface.co/InstantX/InstantID/resolve/main/ControlNetModel/diffusion_pytorch_model.safetensors?download=true

but this model cannot be load successfully. can anyone help ? 

### **Error Log**
2024-02-27 03:10:42,386 - ControlNet - INFO - unit_separate = False, style_align = False
2024-02-27 03:10:42,830 - ControlNet - INFO - Loading model: ip-adapter_instant_id_sdxl [eb2d3ec0]
2024-02-27 03:10:44,452 - ControlNet - INFO - Loaded state_dict from [/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/models/ip-adapter_instant_id_sdxl.bin]
2024-02-27 03:10:47,517 - ControlNet - INFO - ControlNet model ip-adapter_instant_id_sdxl [eb2d3ec0](ControlModelType.IPAdapter) loaded.
2024-02-27 03:10:47,899 - ControlNet - INFO - Using preprocessor: instant_id_face_embedding
2024-02-27 03:10:47,899 - ControlNet - INFO - preprocessor resolution = 512
2024-02-27 03:10:49,030 - ControlNet - INFO - Loading model: control_instant_id_sdxl [c5c25a50]
*** Error running process: /content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py
    Traceback (most recent call last):
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 718, in process
        script.process(p, *script_args)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 1143, in process
        self.controlnet_hack(p)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 1128, in controlnet_hack
        self.controlnet_main_entry(p)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 894, in controlnet_main_entry
        model_net, control_model_type = Script.load_control_model(p, unet, unit.model)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 367, in load_control_model
        control_model = Script.build_control_model(p, unet, model)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 395, in build_control_model
        state_dict = load_state_dict(model_path)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/utils.py", line 21, in load_state_dict
        state_dict = unsafe_torch_load(ckpt_path, map_location=torch.device(location))
      File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 1028, in load
        return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
      File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 1246, in _legacy_load
        magic_number = pickle_module.load(f, **pickle_load_args)
    _pickle.UnpicklingError: invalid load key, '\xd8'.

**Comment by masaisai111** [comment]
Have you solved the problem？

**Comment by hongyuan-wang** [comment]
> Have you solved the problem？

yes, I have already fixed it by adding extension name for file

**Comment by hongyuan-wang** [comment]
already solved
