### ISSUE TITLE
ModuleNotFoundError: No module named 'insightface'

### ISSUE THREAD

**Issue by WannaSir** [InstantID/InstantID#217]
*** Error running process: /data/hdd1/lc/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py
    Traceback (most recent call last):
      File "/data/hdd1/lc/stable-diffusion-webui/modules/scripts.py", line 825, in process
        script.process(p, *script_args)
      File "/data/hdd1/lc/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 1247, in process
        self.controlnet_hack(p)
      File "/data/hdd1/lc/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 1232, in controlnet_hack
        self.controlnet_main_entry(p)
      File "/data/hdd1/lc/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 982, in controlnet_main_entry
        controls, hr_controls, additional_maps = get_control(
      File "/data/hdd1/lc/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 314, in get_control
        controls, hr_controls = list(zip(*[preprocess_input_image(img) for img in optional_tqdm(input_images)]))
      File "/data/hdd1/lc/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 314, in <listcomp>
        controls, hr_controls = list(zip(*[preprocess_input_image(img) for img in optional_tqdm(input_images)]))
      File "/data/hdd1/lc/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 269, in preprocess_input_image
        detected_map = preprocessor.cached_call(
      File "/data/hdd1/lc/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/utils.py", line 81, in decorated_func
        return cached_func(*args, **kwargs)
      File "/data/hdd1/lc/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/utils.py", line 65, in cached_func
        return func(*args, **kwargs)
      File "/data/hdd1/lc/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/supported_preprocessor.py", line 170, in cached_call
        return self(*args, **kwargs)
      File "/data/hdd1/lc/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/preprocessor/legacy/legacy_preprocessors.py", line 97, in __call__
        result, is_image = self.call_function(
      File "/data/hdd1/lc/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/preprocessor/legacy/processor.py", line 740, in run_model_instant_id
        self.load_model()
      File "/data/hdd1/lc/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/preprocessor/legacy/processor.py", line 682, in load_model
        from insightface.app import FaceAnalysis
    ModuleNotFoundError: No module named 'insightface'

**Comment by wangqixun** [comment]
解决方案可否可以换一个🌟

**Comment by WannaSir** [comment]
> 解决方案可否可以换一个🌟

请问怎么解决呀

**Comment by wangqixun** [comment]
> > 解决方案可否可以换一个🌟
> 
> 请问怎么解决呀

pip install insightface

注意选择启动sd webui 的环境

**Comment by soloqi0629** [comment]
> > > 解决方案否可以换一个🌟
> > 
> > 
> > 请问怎么解决呀
> 
> pip 安装 insightface
> 
> 注意选择启动sd webui 的环境

哥，安装完还是一样的问题咋办
