### ISSUE TITLE
AttributeError: 'StableDiffusionXLInstantIDPipeline' object has no attribute 'dtype'

### ISSUE THREAD

**Issue by camoody1** [InstantID/InstantID#65]
Hello... Thank you for all the work you're doing to make this great project happen.

I've been trying all evening to get this to work in my ComfyUI installation. I've tried using both of the Comfy projects you have listed at the bottom of your page (this particular error message is from the ZHO-ZHO-ZHO project). I keep getting the following error message whenever I run either of them:

got prompt
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 155, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 85, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 78, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-InstantID\InstantIDNode.py", line 194, in load_ip_adapter_instantid
    pipe.load_ip_adapter_instantid(face_adapter)
  File "H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-InstantID\pipeline_stable_diffusion_xl_instantid.py", line 156, in load_ip_adapter_instantid
    self.set_image_proj_model(model_ckpt, image_emb_dim, num_tokens)
  File "H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-InstantID\pipeline_stable_diffusion_xl_instantid.py", line 174, in set_image_proj_model
    self.image_proj_model = image_proj_model.to(self.device, dtype=self.dtype)
                                                                   ^^^^^^^^^^
  File "H:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\configuration_utils.py", line 137, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'StableDiffusionXLInstantIDPipeline' object has no attribute 'dtype'

Prompt executed in 24.65 seconds

**Comment by johndpope** [comment]
this belongs in ZHo-Zho-Zho repo. should close - https://github.com/ZHO-ZHO-ZHO/ComfyUI-InstantID
when you boot up do you get errors? you got the dependencies? 
 https://github.com/ZHO-ZHO-ZHO/ComfyUI-InstantID/pull/17

**Comment by camoody1** [comment]
> this belongs in ZHo-Zho-Zho repo. should close - https://github.com/ZHO-ZHO-ZHO/ComfyUI-InstantID when you boot up do you get errors? you got the dependencies? [ZHO-ZHO-ZHO/ComfyUI-InstantID#17](https://github.com/ZHO-ZHO-ZHO/ComfyUI-InstantID/pull/17)

I have no "red" boxes on either of the workflows I have tried. Both error on this node:
![image](https://github.com/InstantID/InstantID/assets/73725653/7777f646-64f0-40a2-9230-a7ae649cbf05)


I get the same error when running the other Comfy project you mentioned in one of your comments.
https://github.com/huxiuhan/comfyui-instantid

**Comment by linjie82** [comment]
Try to upgrade diffusers to version 0.25.0

**Comment by camoody1** [comment]
@linjie82 @johndpope I updated my diffusers to 0.25.0 (the latest, I believe). And I was able to get past my error!

Unnnnfortunately, I ran out of VRAM just before the final image was rendered. The "InstantID Generation" node gets to 100% in the console... there's a slight pause... and then out of vram error. 😭 I have an RTX 3060 12GB card, so I was really hoping I would be able to run this. Alas, I guess not.

**Comment by Blender66Cat** [comment]
upgrade diffusers to version 0.25.1,IT DOSEN'T WORK
![Uploading Snipaste_2024-01-28_14-36-05.png…]()

**Comment by Blender66Cat** [comment]
ERROR:root:Traceback (most recent call last):
  File "F:\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-InstantID\InstantIDNode.py", line 191, in load_ip_adapter_instantid
    pipe.load_ip_adapter_instantid(face_adapter)
  File "F:\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-InstantID\pipeline_stable_diffusion_xl_instantid.py", line 156, in load_ip_adapter_instantid
    self.set_image_proj_model(model_ckpt, image_emb_dim, num_tokens)
  File "F:\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-InstantID\pipeline_stable_diffusion_xl_instantid.py", line 174, in set_image_proj_model
    self.image_proj_model = image_proj_model.to(self.device, dtype=self.dtype)
                                                                   ^^^^^^^^^^
  File "F:\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\configuration_utils.py", line 137, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'StableDiffusionXLInstantIDPipeline' object has no attribute 'dtype'

Prompt executed in 0.40 seconds

**Comment by kidochimney** [comment]
Who can help me?I still got "StableDiffusionXLInstantIDPipeline' object has no attribute 'dtype" after updating my diffusers

**Comment by ResearcherXman** [comment]
Can you share your scripts?

**Comment by camoody1** [comment]
> Try to upgrade diffusers to version 0.25.0

@linjie82 I'm sorry, but I'm a complete idiot with this stuff. Would you mind telling me how to upgrade my diffuers? I see that a new version was just released yesterday that includes InstantID.
