### ISSUE TITLE
 CUDA out of memory. Tried to allocate 14.00 MiB. GPU 0 has a total capacty of 4.00 GiB of which 0 bytes is free. Of the allocated memory 3.41 GiB is allocated by PyTorch, and 65.23 MiB is reserved by PyTorch but unallocated

### ISSUE THREAD

**Issue by GOATGAMER07** [InstantID/InstantID#72]
The config attributes {'controlnet_list': ['controlnet', 'RPMultiControlNetModel'], 'requires_aesthetics_score': False} were passed to StableDiffusionXLInstantIDPipeline, but are not expected and will be ignored. Please verify your model_index.json configuration file.
Keyword arguments {'controlnet_list': ['controlnet', 'RPMultiControlNetModel'], 'requires_aesthetics_score': False, 'safety_checker': None} are not expected by StableDiffusionXLInstantIDPipeline and will be ignored.
Loading pipeline components...: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:03<00:00,  2.03it/s]
LCM
The config attributes {'skip_prk_steps': True} were passed to LCMScheduler, but are not expected and will be ignored. Please verify your scheduler_config.json configuration file.
default: num_inference_steps=2, guidance_scale=2
Traceback (most recent call last):
  File "C:\Users\gibso\pinokio\api\instantid.git\app\app.py", line 91, in <module>
    pipe.cuda()
  File "C:\Users\gibso\pinokio\api\instantid.git\app\pipeline_stable_diffusion_xl_instantid.py", line 489, in cuda
    self.to('cuda', dtype)
  File "C:\Users\gibso\pinokio\api\instantid.git\app\env\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 869, in to
    module.to(device, dtype)
  File "C:\Users\gibso\pinokio\api\instantid.git\app\env\lib\site-packages\torch\nn\modules\module.py", line 1160, in to
    return self._apply(convert)
  File "C:\Users\gibso\pinokio\api\instantid.git\app\env\lib\site-packages\torch\nn\modules\module.py", line 810, in _apply
    module._apply(fn)
  File "C:\Users\gibso\pinokio\api\instantid.git\app\env\lib\site-packages\torch\nn\modules\module.py", line 810, in _apply
    module._apply(fn)
  File "C:\Users\gibso\pinokio\api\instantid.git\app\env\lib\site-packages\torch\nn\modules\module.py", line 810, in _apply
    module._apply(fn)
  [Previous line repeated 7 more times]
  File "C:\Users\gibso\pinokio\api\instantid.git\app\env\lib\site-packages\torch\nn\modules\module.py", line 833, in _apply
    param_applied = fn(param)
  File "C:\Users\gibso\pinokio\api\instantid.git\app\env\lib\site-packages\torch\nn\modules\module.py", line 1158, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
torch.cuda.OutOfMemoryError:![Screenshot 2024-01-25 215131](https://github.com/InstantID/InstantID/assets/157708233/8daffe54-18a0-47a3-9aca-d42e69cd6e34). If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

(env) C:\Users\gibso\pinokio\api\instantid.git\app>

![Screenshot 2024-01-25 215131](https://github.com/InstantID/InstantID/assets/157708233/bf142267-b24d-4789-9905-2374c53692e9)

i have enough resources still getting error

**Comment by GOATGAMER07** [comment]
i have enough resources still getting error

**Comment by haofanwang** [comment]
What's VRAM? 16GB may not be enough, you have to do some optimizations.

**Comment by GOATGAMER07** [comment]
> What's VRAM? 16GB may not be enough, you have to do some optimizations.

understood, i will return to automatic1111 itself which is allows 350x350 photo size pics rendering,☹️🙁😖😞😟

**Comment by tw9mini** [comment]
I'm getting similar error with 12 GB 3060. I tried setting max_split_size_mb to different values to no avail.

torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 11.76 GiB total capacity; 9.33 GiB already allocated; 37.69 MiB free; 9.62 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by astragartist** [comment]
> I'm getting similar error with 12 GB 3060. I tried setting max_split_size_mb to different values to no avail.
> 
> torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 11.76 GiB total capacity; 9.33 GiB already allocated; 37.69 MiB free; 9.62 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation. See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

Same error here!

**Comment by hortom** [comment]
Is it possible to use pruned models for controlnet and IP-Adapter to reduce memory usage?

**Comment by boehm-e** [comment]
I am also very interested to know if it is possible to reduce the amount of vram needed. By pruning, quantizing ?

**Comment by dimtoneff** [comment]
I was able to run it on 12GB 3060. Single generation runs for aprox 1min with 35-40 steps.

pipe.enable_xformers_memory_efficient_attention() on the StableDiffusionXLInstantIDPipeline
            
And before the vae decoding:
self.vae.enable_slicing()
self.vae.enable_tiling()

**Comment by apukale** [comment]
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1.53 GiB. GPU 0 has a total capacty of 6.00 GiB of which 0 bytes is free. Of the allocated memory 12.03 GiB is allocated by PyTorch, and 355.03 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

same error, I have 6GB VRAM 3060. 

Will this never work on 6GB VRAM?

**Comment by hortom** [comment]
Is ControlNet mandatory or it is only for the optional pose image? If it is not mandatory, could it save VRAM if ControlNet model is not loaded and applied?

**Comment by camoody1** [comment]
The VRAM requirements on this seem to be about 14GB. I have 12GB on my 3060 and whether or not my workflow completes is totally hit or miss. Sometimes it runs to completion (very slowly as it has been offloaded to system RAM) and other times, it blows up with an out of memory error after the next to last step hits 100% but before the final image is created. This really needs to be optimized better if at all possible.

**Comment by otukj52** [comment]
return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 14.00 MiB. GPU 0 has a total capacity of 4.00 GiB of which 0 bytes is free. Of the allocated memory 6.97 GiB is allocated by PyTorch, and 184.73 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

![Screenshot 2024-02-01 044722](https://github.com/InstantID/InstantID/assets/126223002/947361cc-0575-4294-804c-909ab835c53c)
 
i dont know what to do i tried many thing even in comfyui i am getting same issue 
i have 1050 4gb vram
